function export_gains(System, L_obs, K, g1, g2, dT)
% export_gains: MATLAB 게인 → YAML 파일로 저장
%
% ROS2 패키지의 config/gains.yaml 로 복사해서 사용
%
% Usage:
%   export_gains(System, L_obs, K, g1, g2)
%
% Output file:
%   gains.yaml  (ROS2 config 폴더에 복사)

%% 출력 경로
out_file = fullfile(fileparts(mfilename('fullpath')), 'gains.yaml');

%% YAML 작성
fid = fopen(out_file, 'w');
if fid == -1
    error('Cannot open file for writing: %s', out_file);
end

fprintf(fid, '# Auto-generated by export_gains.m\n');
fprintf(fid, '# Date: %s\n\n', datestr(now, 'yyyy-mm-dd HH:MM:SS'));

%-- System dimensions --
n = size(System.A, 1);
m = size(System.B, 2);
q = size(System.C, 1);

fprintf(fid, 'system:\n');
fprintf(fid, '  n: %d        # state dimension\n', n);
fprintf(fid, '  m: %d        # control input dimension\n', m);
fprintf(fid, '  q: %d        # output dimension\n', q);
fprintf(fid, '  N: %d        # number of agents\n', size(System.L, 1));
fprintf(fid, '  dT: %.4f    # sampling time [s]\n\n', dT);

%-- SOC parameters --
fprintf(fid, 'soc:\n');
fprintf(fid, '  alpha:   %.6f\n', System.alpha);
fprintf(fid, '  soc_min: %.6f\n', System.soc_min);
fprintf(fid, '  soc_max: %.6f\n\n', System.soc_max);

%-- H-infinity performance --
fprintf(fid, 'hinfinity:\n');
fprintf(fid, '  gamma_obs:  %.8f   # sqrt(g2): observer H-inf index\n', sqrt(g2));
fprintf(fid, '  gamma_ctrl: %.8f   # sqrt(g1): controller H-inf index\n\n', sqrt(g1));

%-- Controller gain K (m x n) --
fprintf(fid, 'K:  # controller gain [%dx%d], row-major\n', m, n);
write_matrix(fid, K);
fprintf(fid, '\n');

%-- Observer gain L_obs (n x q) --
fprintf(fid, 'L_obs:  # observer gain [%dx%d], row-major\n', n, q);
write_matrix(fid, L_obs);
fprintf(fid, '\n');

%-- System matrices --
fprintf(fid, 'A:  # system matrix [%dx%d]\n', n, n);
write_matrix(fid, System.A);
fprintf(fid, '\n');

fprintf(fid, 'B:  # control input matrix [%dx%d]\n', n, m);
write_matrix(fid, System.B);
fprintf(fid, '\n');

fprintf(fid, 'C:  # output matrix [%dx%d]\n', q, n);
write_matrix(fid, System.C);
fprintf(fid, '\n');

%-- Graph Laplacian --
fprintf(fid, 'L_topo:  # graph Laplacian [%dx%d]\n', size(System.L,1), size(System.L,2));
write_matrix(fid, System.L);

fclose(fid);

fprintf('\n[export_gains] 저장 완료: %s\n', out_file);
fprintf('  K     : [%dx%d]\n', size(K));
fprintf('  L_obs : [%dx%d]\n', size(L_obs));
fprintf('  gamma_obs  = %.6f\n', sqrt(g2));
fprintf('  gamma_ctrl = %.6f\n', sqrt(g1));
fprintf('\n→ ROS2 패키지의 config/gains.yaml 로 복사하세요.\n\n');

end

%% -------------------------------------------------------
function write_matrix(fid, M)
[r, c] = size(M);
for i = 1:r
    fprintf(fid, '  - [');
    for j = 1:c
        if j < c
            fprintf(fid, '%.10f, ', M(i,j));
        else
            fprintf(fid, '%.10f', M(i,j));
        end
    end
    fprintf(fid, ']\n');
end
end
